language: ruby
    rvm: 2.5.5p157

os: osx

env:
  global:
    - RAILS_ENV=test # Travisの場合デフォルトでtest
    - secure: "nagaokaVKVsF+w2Vowv1l/hC6p1a7BR8mwonSswcvpdbmz289dFE7oUW7gw3nwzE1lRe71Soh90YqMnGmMY6UASRWHMkDLbf4BACkt4jJKSfQyWRf+J1YmHS8l1lrhk6V+RUsQjNdGbOkuZ5PQVzpwsPzHut4UgrxuLfpW9SkIg="

# featureとtryブランチ以外のブランチは実行対象に入れる
branches:
  except: /^(feature|try).*$/

# masterとdevelopブランチのみ実行対象に入れる
branches:
  only:
    - master
    - develop

script:
  - rspec

deploy:
  provider: heroku
  api_key:
    secure: "6fc77401c785ce000a46aa6353d7494bbedca0c3180dd08c62d4e5179f110565b6bd76773ff6d2938080a172034560778fa050fc04e9d324b2def99a86d39138"
